### ISSUE TITLE
Hexchat disconnects from server when in Oz sandbox

### ISSUE THREAD

**Issue by alisonLFP** [subgraph/subgraph-os-issues#196]
Here's how it goes:
-log in to IRC in hexchat
-connect to server(s)
-immediate disconnection (happens within 1-10 seconds)

This might be related to the issues that OFTC sometimes has in connecting over Tor.

**Comment by ghost** [comment]
+1

**Comment by dma** [comment]
This appears to have been an upstream problem, I reproduced it, but it's fixed now for me. Can anyone verify?

**Comment by alisonLFP** [comment]
Still happening for me, and now the same is true in Icedove. In fact, Icedove won't open at all unless I disable the sandbox. Let me know if you want a separate ticket for that.
