### ISSUE TITLE
Cannot boot Subgraph - Kernel Panic

### ISSUE THREAD

**Issue by Incineroar** [subgraph/subgraph-os-issues#204]
First off, this is an excellent-looking OS that I've been wanting to try for some time. I had an old laptop laying around so I decided to turn it into a secure device by installing Subgraph. However, it's been nothing but issues ever since I started using it.

No matter what I do and what boot method I use (Live, Install first, etc), I cannot get into the OS in any way as I experience a kernel panic (Screenshot here: http://imgur.com/8F9GgL8 - Apologies for the messy screen as it's essentially a wacom tablet). This kernel panic occurs both of the offered live modes and in the OS itself after you perform an installation. Unfortunately, because I don't think I can drop a shell until the OS fully boots (Which also means that I can't access the hard drive's files through another live device since the disk is encrypted), this is about the most of the panic's handling I can capture (Since the device essentially locks up after the kernel panic occurs and the Caps Lock light just sits and flashes on and off). At the bottom it mentions grsec and some kind of strange kernel crash caused by root, so I'm wondering if it's a hardware conflict or if it's perhaps just a one-off error, or if it's just a known issue that's recently been fixed.

The device I'm using is a Lenovo X61 convertible laptop with 4GB RAM, but with a device that's older surely nearly any Linux distro should work on this (Ubuntu 14 works for sure, it was on the device previously). I've gone and tried disabling some of the device's hardware in the BIOS settings, but it doesn't seem to be fixing it. Intel SpeedStep is also disabled so that shouldn't be causing the crash either.

Update: Got it installed on another device, but I'm still having issues with it on both devices. Going to try sorting it out and see if I can get this working on the second device and perhaps create a new issue posting if I can't resolve it.

**Comment by dma** [comment]
Resolved?

**Comment by Incineroar** [comment]
Nope. The device I have this working on right now is an Acer Aspire, but the Lenovo X61 still fails to boot it up. I'll keep trying to troubleshoot it for anyone else wanting to use it on this handy little device.

**Comment by mckinney-subgraph** [comment]
Closing. No further info for us to act upon or reports of other people experiencing the issue.
